
insert into protein_mix.categoria (nombreCategoria,descripcion) values
('Suplementacion en gomitas','¡Obtén los nutrientes de una manera fácil y deliciosa! Sólo consume 4 gomitas al día y empieza a cuidar tu salud.'),
('Infusiones herbales','Disfruta de una bebida rica y saludable en donde quieras.'),
('Antioxidantes e inmunológicos','Evita el daño de los radicales libres en tus células corporales y fortalece tu sistema de defensa.'),
('Articulaciones','Protege al cartílago articular del desgaste generado por la edad o ejercicio con la variedad de suplementos que tenemos para su cuidado.'),
('Cabello, piel, uñas','¡Porque la belleza viene desde adentro! Consume suplementos para mantener una piel joven e hidratada, un cabello saludable, así como uñas fuertes.'),
('Cardiovascular','Ayudan a prevenir enfermedades cardiacas y mejorar la salud del sistema cardiovascular en general.'),
('Control de peso','Contribuyen a adelgazar en conjunto con una alimentación equilibrada y ejercicio.'),
('Digestión','Favorecen el correcto funcionamiento del aparato digestivo para una adecuada absorción de nutrientes.'),
('Energía','¿Te sientes fatigado o cansado? Recupera tu energía con estos suplementos:'),
('Vitaminas y minerales','Dale a tu cuerpo los micronutrientes esenciales para su correcto funcionamiento.'),
('Nutrición deportiva','A ti que te gusta hacer deporte sabes que la suplementación te ayuda a cumplir tus objetivos.'),
('Óseo','Mantén tus huesos fuertes y saludables para hacer lo que mas te gusta.'),
('Superalimentos','Contienen vitaminas, minerales, fitonutrientes y fitoquímicos, que ayudan a protegernos contra las enfermedades.');

insert into protein_mix.producto (nombreProducto,descripcion,precio,stock,idCategoria) values
('Multivitamínico infantil','Frasco con 100 gomitas en forma de oso sabor frutos rojos y limón que contienen Omega 3.',260.00,0,1),
('Glucosamina','Frasco con 150 gomitas sabor cereza que contienen condroitina, vitamina C y vitamina D3.',350.00,0,1),
('Belabear Vitamina E','Frasco con 100 gomitas en forma de oso sabor durazno que contienen colágeno.',260.00,0,1),
('Belabear Vitamina B12','Frasco con 100 gomitas en forma de oso sabor naranja que contienen jalea real y guaraná.',260.00,0,1),
('Belabear Womens Multivitamin','Frasco con 100 gomitas en forma de oso sabor frutos rojos que contienen arándano, colágeno y ácido Fólico.',260.00,0,1),
('Belabear Colágeno','Frasco con 100 gomitas sabor fresa que contienen vitaminas A, C, D3 y ácido fólico.',260.00,0,1),
('Belebear Ácido Hialurónico','Frasco con 100 gomitas sabor frambuesa que contienen granada, mangosteen, noni, goji y colágeno.',260.00,0,1),
('Té de Manzanilla','Caja con 20 sobres para preparar infusión de manzanilla con anís y hierbabuena.',70.00,0,2),
('Té de Limón','Caja con 20 sobres para preparar infusión de té limón con té verde y jamaica.',70.00,0,2),
('Té de Jengibre','Caja con 20 sobres para preparar infusión de jengibre con limón y jazmín.',70.00,0,2),
('Spirulina','Frasco de suplemento alimenticio con 60 cápsulas que contienen diferentes hierbas del mundo.',250.00,0,3),
('Luteína','Matraz con 100 capsulas que contienen vitaminas A, C, E + marigold, bilberry y betacaroteno.',250.00,0,3),
('Vitamina D3','Matraz con 400 cápsulas que contiene vitamina D3 hígado de bacalao.',250.00,0,3),
('Goji + Granada','Matraz de suplemento alimenticio con 100 cápsulas que contienen vitamina A, C, E.',250.00,0,3),
('Ácido Glutámico','Frasco de suplemento alimenticio con 100 cápsulas que contienen lecitina y fósforo.',215.00,0,3),
('Ajox','Matraz con 120 cápsulas de extracto de ajo añejo extracto de shitake, vitamina C, aceite de perejil y orégano.',215.00,0,3),
('Mini caps de Cúrcuma','Matraz con 120 cápsulas que contienen omega 3 (aceite de pescado) y jengibre.',250.00,0,4),
('Cúrcuma','Matraz con 60 cápsulas que contienen omega 3 (aceite de pescado) y jengibre.',250.00,0,4),
('Glucosamina gomitas','Matraz con 150 cápsulas sabor cereza que contienen condroitina, vitamina C y vitamina D3. Sabor cereza.',350.00,0,4),
('Glucosamina','Matraz con 60 cápsulas que contienen glucosamina y omega 3.',215.00,0,4),
('MV-GOM 3','Caja con 20 cápsulas que contienen glucosamina y omega 3 (salmón de Alaska), condroitina y vitamina C.',180.00,0,4),
('Vitamina E','Matraz con 120 cápsulas que contienen biotina.',250.00,0,5),
('Resveratrol','Matraz con 100 cápsulas que contienen coenzima Q-10.',250.00,0,5),
('Colágeno','Matraz con 100 cápsulas que contienen colágeno con extracto de uva Vitaminas A, C, E, luteína y zeaxantina.',250.00,0,5),
('Perlas de Colágeno','Matraz con 180 cápsulas en forma de perla que contienen biotina y CoQ-10',250.00,0,5),
('Biotina','Matraz con 100 cápsulas que contienen biotina y ácido hialurónico.',250.00,0,5),
('Vitamina E','Frasco con 100 cápsulas en forma de oso sabor durazno que contienen Colágeno.',260.00,0,5),
('Belebear Ácido Hialurónico','Frasco con 100 gomitas sabor frambuesa que contienen granada, mangosteen, noni, goji y colágeno.',260.00,0,5),
('Belabear Colágeno','Frasco con 100 gomitas sabor fresa que contienen vitaminas A,C, D3 y ácido fólico.',260.00,0,5),
('Resveratrol','Matraz con 100 cápsulas que contienen coenzima Q-10',250.00,0,6),
('Mix-03 Fitoesteroles','Frasco con 500 g de fibra de avena, linaza, chía, pectina de manzana y papaína. Rinde 33 porciones.',250.00,0,6),
('Omega 3, 6, 9','Caja con 30 cápsulas que contienen aceite natural virgen de linaza, semilla de calabaza, oliva y chía.',180.00,0,6),
('Omega 3 Salmón','Matraz con 120 cápsulas que contienen vitamina E y CoQ-10.',250.00,0,6),
('Krill Rojo Oil','Caja con 30 Softgels de aceite de krill omega 3.',200.00,0,6),
('Aceite de Chía','Matraz con 120 cápsulas que contienen aceite de chía, fuente natural de ácido alfa-linoleico.',215.00,0,6),
('Omega Triplex','Matraz con 60 cápsulas que contienen omega 3, 6, 9.',270.00,0,6),
('Mix-04 Leche de Alpiste','Frasco con 500 g de fibra en polvo sabor coco y vainilla.',250.00,0,7),
('Jugo Verde Mix','Frasco con 500 g de fibra en polvo contiene perejil, piña, apio, chía, nopal, ciruela y té verde.',220.00,0,7),
('Jugo Verde Mix','Caja con 10 sobres para preparar jugo verde contiene perejil, piña, apio, chía, nopal, ciruela y té verde.',200.00,0,7),
('ACG-30','Frasco con 60 cápsulas de medicamento herbolario que ayudan a controlar el peso.',280.00,0,7),
('Jengibre','Caja con 60 cápsulas que contienen jengibre + hinojo.',220.00,0,7),
('Aceite de Coco','Matraz con 120 cápsulas que contienen ácido linoleico conjugado y aceite de chía.',250.00,0,7),
('Aloe Vera','Matraz con 120 cápsulas que contienen zábila + ciruela y lactobacilos.',215.00,0,8),
('Jugo Verde Mix','Frasco con 500 g de fibra en polvo contiene perejil, piña, apio, chía, nopal, ciruela y té verde.',220.00,0,8),
('Jengibre','Caja con 60 cápsulas que contienen jengibre + hinojo.',220.00,0,8),
('Magnesio','Matraz con 100 cápsulas que contienen semilla de Alcaravea.',250.00,0,8),
('Sky Fiber','Frasco de suplemento alimenticio a base de fibra soluble sin gluten, sin azúcar añadida, sin saborizantes.',220.00,0,8),
('Jugo Verde Mix','Caja con 10 sobres para preparar jugo verde contiene perejil, piña, apio, chía, nopal, ciruela y té verde.',200.00,0,8),
('Belabear Vitamina B12','Frasco con 100 gomitas en forma de oso, sabor naranja, que contienen jalea real y guaraná.',260.00,0,9),
('Complejo B','Matraz con 150 cápsulas que contienen complejo B + jalea real.',250.00,0,9),
('Jalea Real','Matraz con 180 cápsulas en forma de perla que contienen jalea real + vitaminas A, C, D, E.',250.00,0,9),
('JR-CB','Caja con 40 cápsulas que contiene jalea real y complejo B.',180.00,0,9),
('Complejo B','Matraz con 150 cápsulas que contienen complejo B + jalea real.',250.00,0,10),
('Belabear Womens Multivitamin','Frasco con 100 gomitas en forma de oso, sabor frutos rojos, que contienen arándano, colágeno y ácido fólico.',260.00,0,10),
('Multisure','Matraz con 60 cápsulas que contienen vitaminas y minerales + omega 3, luteína, licopeno, ácido alfa-lipoico.',290.00,0,10),
('Vitamina C','Frasco con 120 cápsulas que contienen Vitaminas A, D, E, acerola, miel de abeja.',215.00,0,10),
('Soy Protein','Frasco con 420 g de proteína de soya en polvo sabor chocolate.',400.00,0,11),
('Egg Protein','Frasco con 510 g de mezcla de proteínas en polvo sabor chocolate.',410.00,0,11),
('Protein Powder Mix','Frasco con 400 gr de fibra de nopal, chía, perejil, apio, piña, ciruela y té verde, con proteína de chicharon sabor piña.',300.00,0,11),
('L-Carnitina','Matraz con 100 cápsulas que contienen extracto de té verde y vinagre de manzana.',215.00,0,11),
('Calcio','Matraz con 60 cápsulas que contienen vitamina D3 y con magnesio y zinc.',250.00,0,12),
('Calcio de coral','Frasco con 90 cápsulas de calcio de coral + vitamina D.',260.00,0,12),
('Spirulina','Frasco con 60 cápsulas que contienen hierbas del mundo.',250.00,0,13),
('Mix-02 Corazón de Alcachofa','Frasco con 500 g de fibra en polvo sabor toronja.',250.00,0,13),
('Mix-03 Fitoesteroles','Frasco con 500 g de fibra en polvo sabor manzana.',250.00,0,13),
('Mix-04 Leche de Alpiste','Frasco con 500 g de fibra en polvo sabor coco y vainilla.',250.00,0,13),
('Veggie Mix Batido de Verduras','Frasco con 400 g de alimento a base de verdura en polvo y contiene apio, brócoli, espinaca, alfalfa, zanahoria, cilantro, lechuga, pasto de trigo, proteína de chicharo.',330.00,0,13);